# Generated by Django 2.0.5 on 2018-05-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180526_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='team_name',
            field=models.TextField(default='PROJECT Team Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='PROJECT Description'),
        ),
    ]
