# Generated by Django 2.0.5 on 2018-05-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180526_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='projects'),
        ),
    ]
