# Generated by Django 2.0.5 on 2018-05-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180526_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team_name',
            field=models.CharField(max_length=20),
        ),
    ]
